apiVersion: v1

kind: Pod

metadata:
  name: web-demo


spec:

  containers:

  # Main application container
  - name: web-demo

    # image: web-demo:1.0 
    #delete two line bellow and un comment this line above
    image: web-demo
    imagePullPolicy: Never  # Using my local image without checking an online registry 

    volumeMounts:

    - name: shared-logs

      mountPath: /app/logs



  # Sidecar log container
  - name: log-shipper

    # image: log-shipper:1.0
   #delete two line bellow and un comment this line above
    image: web-demo
    imagePullPolicy: Never  # Using my local image without checking an online registry 

    volumeMounts:

    - name: shared-logs

      mountPath: /var/log/incoming



  # Shared temporary storage
  volumes:

  - name: shared-logs

    emptyDir: {}
