apiVersion: v1                       
kind: Pod                            
metadata:                           
  name: web-demo                     
  labels:                           
    app: web-demo                                    
spec:                                
  containers:                        
    - name: web-demo                 
      image: web-demo
      imagePullPolicy: Never  # Uses your local image without checking an online registry        
      ports:                         
        - containerPort: 8080        
